### ISSUE TITLE
Replace Better Recent Comments issue in next update

### ISSUE THREAD

**Issue by KatieKeith** [andykeith/better-recent-comments#10]
There's a minor typo in the main image at the top of the BRC wordpress.org page, please replace it with the attached next time you do an update. 
![better-recent-comments](https://user-images.githubusercontent.com/45937378/214250919-d0e92a65-317d-4a66-a75e-0132367a98c2.png)

**Comment by amirition** [comment]
Resolved in version 1.1.7
