### ISSUE TITLE
Windows line ends

### ISSUE THREAD

**Issue by szepeviktor** [andykeith/better-recent-comments#16]
There are CRLF line ends committed to the repository.

Windows may be popular but Microsoft is the only company not using LF line ends.
Git clients could be configured to handle line end conversion on checkout/commit.

**Comment by szepeviktor** [comment]
The Integrity workflow keeps an eye on this too.
https://github.com/szepeviktor/byte-level-care/blob/master/.github/workflows/integrity.yml

**Comment by andykeith** [comment]
Thanks for the report. @amirition Could you fix this at some point?

**Comment by szepeviktor** [comment]
Try [`.editorconfig`](https://github.com/szepeviktor/byte-level-care/blob/5a85fbe55c265f2300a99069f9f7af6df2fb42f0/.editorconfig#L1-L15) with the six keys and https://github.com/greut/eclint

**Comment by amirition** [comment]
I have globally updated my git client, so this should not happen again.
